apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
    pod: mypod
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
        about: expressServer
    spec:
      containers:
        - name: myapp
          image: nginx
