apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  labels:
    app: test-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
