apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    app: test-storage
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage # 👈 Storage is provided by the local file system or disk of the node where the pod is running. If the pod moves to another node, it loses access to the storage unless explicitly configured.
  hostPath:
    path: /Users/akhilgireesh/Programming/k8/staticVol
