apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    app: test-storage
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /Users/akhilgireesh/Programming/k8/staticVol
