apiVersion: v1
kind: Service
metadata:
  name: db # As worker connects to postgres using the term db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
